# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rdo8mafsGvsHBo1IMV0i_r7cxyUvTZAA
"""



from google.colab import drive
drive.mount('/gdrive')

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext autoreload
# %autoreload 2
# %matplotlib inline

from fastai import *
from fastai.vision import *
from fastai.metrics import error_rate, accuracy
import gdown

IMG = '/content/drive/My Drive/PlantVillage (1)'

bs = 64 # batch_size

img_data = ImageDataBunch.from_folder(path=IMG, train='train', valid='val', ds_tfms=get_transforms(), size=224)

img_data.normalize(imagenet_stats)

img_data.show_batch(rows=3, figsize=(10,8))

img_data.c

img_data.classes

model = cnn_learner(img_data, models.resnet34, metrics=[accuracy, error_rate])

model.fit_one_cycle(5)

model.fit_one_cycle(2)

model.save('train_7_cycles')

interpret = ClassificationInterpretation.from_learner(model)

interpret.plot_top_losses(4, figsize=(20, 25))

interpret.plot_confusion_matrix(figsize=(20,20), dpi=60)

model.lr_find()

model.recorder.plot()

model.unfreeze()
model.fit_one_cycle(3, max_lr=slice(1e-03, 1e-02))

model.fit_one_cycle(5, max_lr=slice(1e-03, 1e-02))

model.save('train_lr_8_cycles')

model.freeze()
model.lr_find()
model.recorder.plot()

lr = 1e-3/2
model.fit_one_cycle(2, slice(lr))

model.fit_one_cycle(3, slice(lr))

model.save('train_final5_cycles')

model.load('train_final5_cycles')

model.export('export_resnet34_model.pkl')

from google.colab import files
files.download('export_resnet34_model.pkl')

img1=open_image('/content/drive/My Drive/PlantVillage (1)/val/Apple___Black_rot/0139bc6d-391c-4fd1-bcae-cc74dabfddd7___JR_FrgE.S 2734.JPG')
learn = load_learner(IMG,'export_resnet34_model.pkl')

pred_class,pred_idx,outputs = learn.predict(img1)
pred_class

pred_class=''
img1=open_image('/content/drive/My Drive/PlantVillage (1)/val/Apple___Cedar_apple_rust/025b2b9a-0ec4-4132-96ac-7f2832d0db4a___FREC_C.Rust 3655.JPG')
learn = load_learner(IMG,'export_resnet34_model.pkl')

pred_class,pred_idx,outputs = learn.predict(img1)
pred_class